modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="Saereth"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${mod_loader_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="actuallyadditions"
type="required"
versionRange="[1.3.0,)"
ordering="AFTER"
side="BOTH"
